# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170224_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='questionset_result',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questionset_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='question_title',
            field=models.CharField(max_length=1000),
        ),
    ]
